apiVersion: autoscaling/v2beta1  #从这可以看出是hpa v2版本
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa-v2
spec:
  scaleTargetRef: #根据什么指标来做评估压力
    apiVersion: apps/v1 #对谁来做自动扩展
    kind: Deployment
    name: myapp
  minReplicas: 1 #最少副本数量
  maxReplicas: 10
  metrics: #表示依据哪些指标来进行评估
  - type: Pods #表示基于资源进行评估
    pods: 
      metricName: http_requests#自定义的资源指标
        targetAverageValue: 800m #m表示个数,表示并发数800
