apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-nfs
  namespace: default
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    volumeMounts:
    - name: html
      mountPath: /usr/shar/nginx/html/
  volumes:
  - name: html
    nfs:
      path: /data/volumes
      server: 172.16.100.64
