apiVersion: v1
kind: Pod
metadata:
    name: pod-demo
    namespace: default
    labels:
        app: myapp
        tier: forntend
    annotations:
        lihongxing.com/created-by: cluster admin
spec:
    containers:
    - name: myapp
      image: ikubernetes/myapp:v1
    - name: busybox
      image: busybox:latest
      command: 
      - "/bin/sh"
      - "-c"
      - "sleep 3600"
        
    nodeSelector:
        disktype: ssd
