apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    app: myapp
    relase: canary
  clusterIP:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
