apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis
    role: logstor
  clusterIP:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
